name: Sync from Shopify Upstream

on:
  schedule:
    - cron: '0 4 * * *'    # Kjør daglig kl 04:00 UTC
  workflow_dispatch:        # Manuell kjøring fra GitHub

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Shopify/product-taxonomy.git
          git fetch upstream

      - name: Merge upstream into main
        run: |
          git checkout main
          git merge upstream/main --no-edit || echo "No changes to merge"

      - name: Push changes to your fork
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
